import type { Metadata } from "next";
// import '@fortawesome/fontawesome-svg-core/styles.css';
import { Toaster } from 'react-hot-toast'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './(components)/Navbar';
import Scripts from './(components)/Scripts';
import Footer from "./(components)/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${inter.className} antialiased min-vh-100 d-flex flex-column`} style={{ backgroundColor: '#222222' }}>
        <Navbar />
        {children}
        <Toaster />
        <Scripts />
        <Footer/>
      </body>

    </html>
  );
}
